---
title: "Proposal Code"
subtitle: ""
author:
  - name: Luis Hernandez
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
---

```{r setup}
if (!require("pacman")) 
  install.packages("pacman")

# use this line for installing/loading
pacman::p_load(tidyverse,
               ggthemes,
               patchwork,
               pokemon)

# set theme for ggplot2
ggplot2::theme_set(ggplot2::theme_grey(base_size = 12))

# set figure parameters for knitr
knitr::opts_chunk$set(
  fig.width = 7, # 7" width
  fig.asp = 0.618, # the golden ratio
  fig.retina = 3, # dpi multiplier for displaying HTML output on retina
  fig.align = "center", # center align figures
  dpi = 300 # higher dpi, sharper image
)



```

## 0 - Pre Process

```{r cache=TRUE}
#| label: Pre Process

pokemon_data <- pokemon

pokemon_data <- pokemon_data |>
  rename(generation = generation_id)

#Trimming specific columns that will not be needed for the analysis
pokemon_data$id <- NULL
pokemon_data$species_id <- NULL
pokemon_data$base_experience <- NULL

pokemon_data$egg_group_1 <- NULL
pokemon_data$egg_group_2 <- NULL

pokemon_data$color_1 <- NULL
pokemon_data$color_2 <- NULL
pokemon_data$color_f <- NULL

pokemon_data$url_icon <- NULL
pokemon_data$url_image <- NULL

#Removing Pokemon without a generation ID
#Referenced https://tidyr.tidyverse.org/reference/drop_na.html

pokemon_data <- pokemon_data |>
  drop_na(generation)

#Referenced: https://infopoke.net/pokedex/legendary
#Data does not include indicator for legendary/mythical status. 
#This means I need to manually sort which Pokemon are legendary/mythical
pokemon_data <- pokemon_data |>
  mutate(
    legend_stat = case_when(
      row_number() %in% 
        c(144, 145, 146, 150, 151, 243, 
          244, 245, 249, 250, 251, 377, 
          378, 379, 380, 381, 382, 383, 
          384, 385, 386, 480, 481, 482, 
          483, 484, 485, 486, 487, 488, 
          489, 490, 491, 492, 493, 494, 
          638, 639, 640, 641, 642, 643, 
          644, 645, 646, 647, 648, 649, 
          716, 717, 718, 719, 720, 721, 
          785, 786, 787, 788, 791, 792, 
          800, 801, 802 ) ~ TRUE,
          TRUE  ~ FALSE
    ),
    
    total_stats = rowSums(across(c(hp, attack, defense, special_attack, special_defense, speed)))
    
  )

special_pokemon <- pokemon_data |>
  filter(legend_stat == TRUE)

regular_pokemon <- pokemon_data |>
  filter(legend_stat == FALSE)

type_colors <-  
  c(
    "normal" = "gray50",
    "fighting" = "darkorange",
    "flying" = "lightskyblue3",
    "poison" = "mediumpurple",
    "ground" = "sienna",
    "rock" = "tan",
    "bug" = "darkolivegreen3",
    "ghost" = "purple4",
    "steel" = "slategray",
    "fire" = "red3",
    "water" = "dodgerblue3",
    "grass" = "seagreen4",
    "electric" = "goldenrod",
    "psychic" = "deeppink3",
    "ice" = "cyan3",
    "dragon" = "steelblue3",
    "dark" = "grey30",
    "fairy" = "plum3"
  )


```

```{r}
#| label: Type Code

#Need to account for secondary typing of Pokemon, so we're pivoting both type columns into one
pokemon_data_longer <- pokemon_data |>
  pivot_longer(
    cols = starts_with("type_"),
    values_to = "types"
  ) |>
#Some Pokemon only have a single type, which causes NA values to show up when the data is pivoted
  drop_na(types)

pokemon_data_longer |> ggplot(aes(y =  fct_rev(fct_infreq(types)), fill = types)) +
  geom_bar() +
#Referenced: https://stackoverflow.com/questions/63653351/how-to-use-stat-count-to-label-a-bar-chart-with-counts-or-percentages-in-ggplo
  scale_fill_manual(values = type_colors) +
  geom_text(
    aes(label = after_stat(count)),
    stat = "count", hjust = 1.1, size = 3,
    color = "white"
  ) +
  labs(
    title = "Total Number of Pokemon Type Occurrences",
    subtitle = "Data up to Pokemon Sun & Moon (2016)",
    caption = "Data source: https://github.com/williamorim/pokemon/",
    x = "Type Count",
    y = "Type"
  ) +
  theme(
    legend.position = "none",
  )
```

```{r}
#| label: Type Code 2

#Need to account for secondary typing of Pokemon, so we're pivoting both type columns into one
regular_pokemon_data_longer <- regular_pokemon |>
  pivot_longer(
    cols = starts_with("type_"),
    values_to = "types"
  ) |>
#Some Pokemon only have a single type, which causes NA values to show up when the data is pivoted
  drop_na(types)

#Getting numerical value for every type per generation
regular_type_count  <- regular_pokemon_data_longer |>
  count(generation, types)
#-------------------------------------------------------------------------------------------------------#
#Legendary/Mythical Pokemon

special_pokemon_data_longer <- special_pokemon |>
  pivot_longer(
    cols = starts_with("type_"),
    values_to = "types"
  ) |>
  drop_na(types)

special_type_count  <- special_pokemon_data_longer |>
  count(generation, types)


#-------------------------------------------------------------------------------------------------------#
  
regular_type_count |> ggplot(
  aes(x = generation, 
      y = n,
      color = types,
      group = types
      )
  ) +
  geom_point(size = 1) +
  geom_line(linewidth = 0.5, alpha = 0.5) +
  scale_color_manual(values = type_colors) +
  scale_x_continuous(breaks = regular_type_count$generation) +
#Referenced: https://stackoverflow.com/questions/63653351/how-to-use-stat-count-to-label-a-bar-chart-with-counts-or-percentages-in-ggplo
  labs(
    title = "Total Number of Type Occurrences by Generation\nfor non-Legendary/Mythical Pokemon",
    subtitle = "Data up to Pokemon Sun & Moon (2016)",
    caption = "Data source: https://github.com/williamorim/pokemon/",
    x = "Generation",
    y = "Type Count"
  ) +
  theme(
    legend.position = "right",
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 10),
  ) + 
  guides(
     color = guide_legend(override.aes = list(size = 1), ncol = 2) 
  )

#-------------------------------------------------------------------------------------------------------#

special_type_count |> ggplot(
  aes(x = generation, 
      y = n,
      color = types,
      group = types
      )
  ) +
  geom_point(size = 1) +
  geom_line(linewidth = 0.5, alpha = 0.5) +
  scale_color_manual(values = type_colors) +
  scale_x_continuous(breaks = special_type_count$generation) +
#Referenced: https://stackoverflow.com/questions/63653351/how-to-use-stat-count-to-label-a-bar-chart-with-counts-or-percentages-in-ggplo
  labs(
    title = "Total Number of Type Occurrences by Generation\nfor Legendary/Mythical Pokemon",
    subtitle = "Data up to Pokemon Sun & Moon (2016)",
    caption = "Data source: https://github.com/williamorim/pokemon/",
    x = "Generation",
    y = "Type Count"
  ) +
  theme(
    legend.position = "right",
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 10),
  ) + 
  guides(
     color = guide_legend(override.aes = list(size = 1), ncol = 2) 
  )

  
```

## 2. Stats

```{r}
#| label: Stat Code

generation_averages <- pokemon_data |>
  group_by(generation) |>
  summarise(avg_tot_stats = mean(total_stats),
            avg_height = mean(height),
            avg_weight = mean(weight)
            ) |>
  pivot_longer(
    cols = starts_with("avg_"),
    values_to = "averages"
  ) |>
  mutate(
    name = recode(factor(name),
      "avg_tot_stats" = "Total Stats",
      "avg_height" = "Height (M)",
      "avg_weight" = "Weight (Kg)"
      )
  )

#-------------------------------------------------------------------------------------------------------#

generation_averages |> ggplot(
  aes(
    x = generation,
    y = averages,
    )
  ) +
  geom_point(size = 1, alpha = 0.75) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_continuous(breaks = generation_averages$generation) +
    labs(
    title = "Average Values by Generation",
    subtitle = "Data up to Pokemon Sun & Moon (2016)",
    caption = "Data source: https://github.com/williamorim/pokemon/",
    x = "Generation",
    y = "Average Value"
  ) +
  theme(
    legend.text = element_text(size = 9),
    legend.title = element_text(size = 10),
  ) +
  #Referenced: https://ggplot2.tidyverse.org/reference/facet_wrap.html
  facet_wrap(
    ~ fct_inorder(name),
    labeller = labeller(name = new_labels),
    scales = "free_y",
    nrow = 3
  )

#-------------------------------------------------------------------------------------------------------#

```
